# Generated by Django 4.2.7 on 2023-11-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['sequence_number']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['sequence_number']},
        ),
        migrations.AddField(
            model_name='photo',
            name='sequence_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
