# Generated by Django 4.2.7 on 2023-11-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_photo_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
