# Generated by Django 4.2.7 on 2023-12-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_photo_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('link', models.CharField(max_length=512)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Новинка',
                'verbose_name_plural': 'Новинки',
                'ordering': ['-update_at'],
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default='name', max_length=512, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
